Get the basic commit-locally-and-push workflow operational
The first git commit + push of the "unalderated nexson" works, but the line:

    add_or_replace_annotation(rich_nexson, annotation)

causes a

    TypeError: 'NexSON' object is not subscriptable